name: Publish to GitHub.com

on:
  push:
    branches:
      - dev
    paths-ignore:
      - "README.md"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Nerdbank.GitVersioning to set version variables
        uses: aarnott/nbgv@v0.3
        with:
          setAllVars: true
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.302"

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.1

      - name: MSBuild Restore x86
        run: msbuild /t:restore /p:Configuration=ReleaseNuGet /p:Platform="x86" ColorPicker.sln

      - name: MSBuild Build x86
        run: msbuild /p:Configuration=ReleaseNuGet /p:Platform="x86" ColorPicker.sln

      - name: MSBuild Restore x64
        run: msbuild /t:restore /p:Configuration=ReleaseNuGet /p:Platform="x64" ColorPicker.sln

      - name: MSBuild Build x64
        run: msbuild /p:Configuration=ReleaseNuGet /p:Platform="x64" ColorPicker.sln

      - name: MSBuild Restore ARM
        run: msbuild /t:restore /p:Configuration=ReleaseNuGet /p:Platform="ARM" ColorPicker.sln

      - name: MSBuild Build ARM
        run: msbuild /p:Configuration=ReleaseNuGet /p:Platform="ARM" ColorPicker.sln

      - name: MSBuild Restore ARM64
        run: msbuild /t:restore /p:Configuration=ReleaseNuGet /p:Platform="ARM64" ColorPicker.sln

      - name: MSBuild Build ARM64
        run: msbuild /p:Configuration=ReleaseNuGet /p:Platform="ARM64" ColorPicker.sln

      - name: Setup Nuget.exe
        uses: nuget/setup-nuget@v1

      - name: Pack
        run: nuget pack ColorPicker.nuspec -version ${{ env.NBGV_Version }}-rc

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.NBGV_Version }}-rc
          release_name: v${{ env.NBGV_Version }}-rc
          draft: false
          prerelease: true

      - name: Update release asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ColorPicker.Xamarin.Forms.${{ env.NBGV_Version }}-rc.nupkg
          asset_name: ColorPicker.Xamarin.Forms.${{ env.NBGV_Version }}-rc.nupkg
          asset_content_type: application/nupkg
